/* === app.js — Apache Hive Analytics Dashboard === */

// Load data from the JSON file generated by aggregate_data.py
fetch('analytics_data.json')
  .then(r => r.json())
  .then(DATA => init(DATA))
  .catch(() => {
    document.body.innerHTML = '<div style="color:#ef4444;text-align:center;margin-top:20vh;font-size:18px;">⚠️ Could not load analytics_data.json.<br>Run <code>python aggregate_data.py</code> first, then serve via a local server.</div>';
  });

// ── Chart.js global defaults ──────────────────────────────────────
Chart.defaults.color = '#7c6fa0';
Chart.defaults.font.family = 'Inter';
Chart.defaults.plugins.legend.labels.boxWidth = 12;
Chart.defaults.plugins.legend.labels.padding = 14;

const PALETTE = ['#9b87f5','#f472b6','#34d399','#fb923c','#38bdf8','#f87171','#fcd34d','#a78bfa','#4ade80','#e879f9'];
const GRID_COLOR = 'rgba(196,181,253,.25)';

function gridOpts() {
  return { color: GRID_COLOR, drawBorder: false, borderDash: [4,4] };
}
function tickOpts() {
  return { color: '#7c6fa0', font: { size: 11, family: 'Inter' } };
}

// ── Number formatters ─────────────────────────────────────────────
const fmtCur = v => '$' + (v >= 1e6 ? (v/1e6).toFixed(2)+'M' : v >= 1e3 ? (v/1e3).toFixed(1)+'K' : v.toFixed(0));
const fmtNum = v => v >= 1e6 ? (v/1e6).toFixed(2)+'M' : v >= 1e3 ? (v/1e3).toFixed(1)+'K' : String(v);
const fmtPct = v => v.toFixed(1) + '%';

// ── Tooltip factory ───────────────────────────────────────────────
function tooltip(currency = false) {
  return {
    backgroundColor: '#ffffff',
    borderColor: '#ddd6f3',
    borderWidth: 1,
    titleColor: '#2d2154',
    bodyColor: '#7c6fa0',
    padding: 12,
    cornerRadius: 10,
    boxShadow: '0 4px 16px rgba(155,135,245,.15)',
    callbacks: {
      label: ctx => {
        const v = ctx.parsed.y !== undefined ? ctx.parsed.y : ctx.parsed;
        return `  ${ctx.dataset.label || ctx.label}: ${currency ? fmtCur(v) : fmtNum(v)}`;
      }
    }
  };
}

// ─────────────────────────────────────────────────────────────────
function init(DATA) {

  // Update time
  document.getElementById('updateTime').textContent = new Date().toLocaleTimeString();

  buildKPIs(DATA);
  buildOverviewCharts(DATA);
  buildRevenueCharts(DATA);
  buildCategorySection(DATA);
  buildGeographySection(DATA);
  buildCustomerSection(DATA);
  buildSensorSection(DATA);
  buildQuerySection();
  setupNav();
  setupMenu();
}

// ── KPI Cards ─────────────────────────────────────────────────────
function buildKPIs(D) {
  const grid = document.getElementById('kpiGrid');
  const kpis = [
    { icon:'💰', label:'Total Revenue', value: fmtCur(D.kpis.total_revenue), sub:'Completed orders only', cls:'lavender' },
    { icon:'🛒', label:'Total Orders',  value: fmtNum(D.kpis.total_orders),   sub:'From 50,000 transactions', cls:'sky' },
    { icon:'👥', label:'Customers',     value: fmtNum(D.kpis.unique_customers), sub:'Active buyers', cls:'mint' },
    { icon:'📈', label:'Avg Order Value', value: fmtCur(D.kpis.aov), sub:'Per completed order', cls:'rose' },
    { icon:'📦', label:'Units Sold',    value: fmtNum(D.kpis.units_sold),     sub:'Total items dispatched', cls:'peach' },
    { icon:'🚨', label:'Sensor Alerts', value: fmtNum(D.kpis.total_alerts),   sub:'IoT anomalies detected', cls:'coral' },
  ];
  grid.innerHTML = kpis.map(k => `
    <div class="kpi-card ${k.cls}">
      <div class="kpi-icon">${k.icon}</div>
      <div class="kpi-label">${k.label}</div>
      <div class="kpi-value">${k.value}</div>
      <div class="kpi-sub">${k.sub}</div>
    </div>`).join('');
}

// ── OVERVIEW CHARTS ───────────────────────────────────────────────
function buildOverviewCharts(D) {
  // Monthly Revenue
  new Chart('monthlyChart', {
    type: 'line',
    data: {
      labels: D.monthly.map(m => m.month),
      datasets: [{
        label: 'Revenue',
        data: D.monthly.map(m => m.revenue),
        borderColor: '#9b87f5',
        backgroundColor: 'rgba(155,135,245,.1)',
        tension: .4,
        fill: true,
        pointBackgroundColor: '#ffffff',
        pointBorderColor: '#9b87f5',
        pointBorderWidth: 2,
        pointRadius: 5,
      }]
    },
    options: {
      responsive: true,
      plugins: { legend: { display: false }, tooltip: tooltip(true) },
      scales: {
        x: { grid: { display: false }, ticks: tickOpts() },
        y: { grid: gridOpts(), ticks: { ...tickOpts(), callback: fmtCur } }
      }
    }
  });

  // Status Doughnut
  new Chart('statusChart', {
    type: 'doughnut',
    data: {
      labels: D.status.map(s => s.status),
      datasets: [{ data: D.status.map(s => s.count), backgroundColor: PALETTE, borderWidth: 0 }]
    },
    options: {
      responsive: true,
      cutout: '65%',
      plugins: { legend: { position: 'bottom' }, tooltip: tooltip() }
    }
  });

  // Device Bar
  new Chart('deviceChart', {
    type: 'bar',
    data: {
      labels: D.devices.map(d => d.device),
      datasets: [{
        label: 'Orders',
        data: D.devices.map(d => d.orders),
        backgroundColor: ['#f5b942','#3b82f6','#10b981'],
        borderRadius: 7
      }]
    },
    options: {
      responsive: true,
      plugins: { legend: { display: false }, tooltip: tooltip() },
      scales: {
        x: { grid: { display: false }, ticks: tickOpts() },
        y: { grid: gridOpts(), ticks: tickOpts() }
      }
    }
  });

  // Payment Bar
  new Chart('paymentChart', {
    type: 'bar',
    data: {
      labels: D.payment.map(p => p.method),
      datasets: [{
        label: 'Revenue',
        data: D.payment.map(p => p.revenue),
        backgroundColor: PALETTE,
        borderRadius: 7
      }]
    },
    options: {
      indexAxis: 'y',
      responsive: true,
      plugins: { legend: { display: false }, tooltip: tooltip(true) },
      scales: {
        x: { grid: gridOpts(), ticks: { ...tickOpts(), callback: fmtCur } },
        y: { grid: { display: false }, ticks: tickOpts() }
      }
    }
  });

  // Hourly Line
  new Chart('hourlyChart', {
    type: 'line',
    data: {
      labels: D.hourly.map(h => h.hour + ':00'),
      datasets: [{
        label: 'Orders',
        data: D.hourly.map(h => h.orders),
        borderColor: '#f472b6',
        backgroundColor: 'rgba(244,114,182,.1)',
        fill: true,
        tension: .3,
        pointRadius: 2,
        pointBackgroundColor: '#f472b6'
      }]
    },
    options: {
      responsive: true,
      plugins: { legend: { display: false }, tooltip: tooltip() },
      scales: {
        x: { grid: { display: false }, ticks: tickOpts() },
        y: { grid: gridOpts(), ticks: tickOpts() }
      }
    }
  });
}

// ── REVENUE CHARTS ────────────────────────────────────────────────
function buildRevenueCharts(D) {
  // Dual axis
  new Chart('dualAxisChart', {
    type: 'bar',
    data: {
      labels: D.monthly.map(m => m.month),
      datasets: [
        {
          label: 'Revenue', type: 'bar',
          data: D.monthly.map(m => m.revenue),
          backgroundColor: 'rgba(155,135,245,.35)',
          borderColor: '#9b87f5',
          borderWidth: 1.5,
          borderRadius: 8,
          yAxisID: 'y'
        },
        {
          label: 'Orders', type: 'line',
          data: D.monthly.map(m => m.orders),
          borderColor: '#f472b6',
          backgroundColor: 'rgba(244,114,182,.08)',
          fill: true,
          tension: .4,
          pointRadius: 4,
          pointBackgroundColor: '#ffffff',
          pointBorderColor: '#f472b6',
          pointBorderWidth: 2,
          yAxisID: 'y1'
        }
      ]
    },
    options: {
      responsive: true,
      plugins: { tooltip: { mode: 'index', intersect: false } },
      scales: {
        x: { grid: { display: false }, ticks: tickOpts() },
        y:  { grid: gridOpts(), ticks: { ...tickOpts(), callback: fmtCur }, position: 'left' },
        y1: { grid: { display: false }, ticks: tickOpts(), position: 'right' }
      }
    }
  });

  // Discount bucket
  new Chart('discountChart', {
    type: 'bar',
    data: {
      labels: D.discount_buckets.map(d => d.bucket),
      datasets: [{
        label: 'Orders',
        data: D.discount_buckets.map(d => d.orders),
        backgroundColor: ['#10b981','#3b82f6','#a855f7','#f5b942','#ef4444'],
        borderRadius: 7
      }]
    },
    options: {
      responsive: true,
      plugins: { legend: { display: false }, tooltip: tooltip() },
      scales: {
        x: { grid: { display: false }, ticks: tickOpts() },
        y: { grid: gridOpts(), ticks: tickOpts() }
      }
    }
  });

  // Warehouse revenue
  new Chart('warehouseRevChart', {
    type: 'bar',
    data: {
      labels: D.warehouses.map(w => w.warehouse),
      datasets: [{
        label: 'Revenue',
        data: D.warehouses.map(w => w.revenue),
        backgroundColor: ['#9b87f5','#f472b6','#34d399','#fb923c','#38bdf8'],
        borderRadius: 9
      }]
    },
    options: {
      responsive: true,
      plugins: { legend: { display: false }, tooltip: tooltip(true) },
      scales: {
        x: { grid: { display: false }, ticks: tickOpts() },
        y: { grid: gridOpts(), ticks: { ...tickOpts(), callback: fmtCur } }
      }
    }
  });

  // Cumulative running total
  let cum = 0;
  const cumData = D.monthly.map(m => { cum += m.revenue; return Math.round(cum); });
  new Chart('cumulativeChart', {
    type: 'line',
    data: {
      labels: D.monthly.map(m => m.month),
      datasets: [{
        label: 'Cumulative Revenue',
        data: cumData,
        borderColor: '#34d399',
        backgroundColor: 'rgba(52,211,153,.1)',
        fill: true,
        tension: .4,
        pointBackgroundColor: '#ffffff',
        pointBorderColor: '#34d399',
        pointBorderWidth: 2,
        pointRadius: 4
      }]
    },
    options: {
      responsive: true,
      plugins: { legend: { display: false }, tooltip: tooltip(true) },
      scales: {
        x: { grid: { display: false }, ticks: tickOpts() },
        y: { grid: gridOpts(), ticks: { ...tickOpts(), callback: fmtCur } }
      }
    }
  });
}

// ── CATEGORY SECTION ──────────────────────────────────────────────
function buildCategorySection(D) {
  new Chart('categoryBarChart', {
    type: 'bar',
    data: {
      labels: D.categories.map(c => c.category),
      datasets: [{
        label: 'Revenue',
        data: D.categories.map(c => c.revenue),
        backgroundColor: PALETTE,
        borderRadius: 7
      }]
    },
    options: {
      responsive: true,
      plugins: { legend: { display: false }, tooltip: tooltip(true) },
      scales: {
        x: { grid: { display: false }, ticks: { ...tickOpts(), maxRotation: 30 } },
        y: { grid: gridOpts(), ticks: { ...tickOpts(), callback: fmtCur } }
      }
    }
  });

  new Chart('categoryPieChart', {
    type: 'pie',
    data: {
      labels: D.categories.map(c => c.category),
      datasets: [{ data: D.categories.map(c => c.revenue), backgroundColor: PALETTE, borderWidth: 0 }]
    },
    options: {
      responsive: true,
      plugins: { legend: { position: 'bottom', labels: { font: { size: 11 } } }, tooltip: tooltip(true) }
    }
  });

  // Table
  const maxRev = Math.max(...D.categories.map(c => c.revenue));
  const rows = D.categories.map((c, i) => {
    const pct = ((c.revenue / maxRev) * 100).toFixed(0);
    const rankClass = i === 0 ? 'rank-1' : i === 1 ? 'rank-2' : i === 2 ? 'rank-3' : '';
    return `<tr>
      <td><span class="rank-badge ${rankClass}">${i+1}</span></td>
      <td>${c.category}</td>
      <td><div class="bar-cell"><div class="bar-bg"><div class="bar-fill" style="width:${pct}%"></div></div>${fmtCur(c.revenue)}</div></td>
      <td>${fmtNum(c.orders)}</td>
      <td>${fmtNum(c.units)}</td>
    </tr>`;
  }).join('');
  document.getElementById('categoryTable').innerHTML = `
    <table>
      <thead><tr><th>#</th><th>Category</th><th>Revenue</th><th>Orders</th><th>Units Sold</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
}

// ── GEOGRAPHY ─────────────────────────────────────────────────────
function buildGeographySection(D) {
  new Chart('regionBarChart', {
    type: 'bar',
    data: {
      labels: D.regions.map(r => r.region),
      datasets: [{
        label: 'Revenue',
        data: D.regions.map(r => r.revenue),
        backgroundColor: PALETTE,
        borderRadius: 7
      }]
    },
    options: {
      indexAxis: 'y',
      responsive: true,
      plugins: { legend: { display: false }, tooltip: tooltip(true) },
      scales: {
        x: { grid: gridOpts(), ticks: { ...tickOpts(), callback: fmtCur } },
        y: { grid: { display: false }, ticks: tickOpts() }
      }
    }
  });

  new Chart('regionPieChart', {
    type: 'doughnut',
    data: {
      labels: D.regions.map(r => r.region),
      datasets: [{ data: D.regions.map(r => r.revenue), backgroundColor: PALETTE, borderWidth: 0 }]
    },
    options: {
      responsive: true,
      cutout: '60%',
      plugins: { legend: { position: 'bottom' }, tooltip: tooltip(true) }
    }
  });
}

// ── CUSTOMERS ─────────────────────────────────────────────────────
function buildCustomerSection(D) {
  new Chart('segmentChart', {
    type: 'doughnut',
    data: {
      labels: D.segments.map(s => s.segment),
      datasets: [{ data: D.segments.map(s => s.revenue), backgroundColor: ['#f5b942','#3b82f6','#10b981'], borderWidth: 0 }]
    },
    options: {
      responsive: true,
      cutout: '60%',
      plugins: { legend: { position: 'bottom' }, tooltip: tooltip(true) }
    }
  });

  // Segment trend (simulated per‑month using overall monthly split)
  const totalSeg = D.segments.reduce((a, s) => a + s.revenue, 0);
  const segColors = { Premium: '#9b87f5', Regular: '#f472b6', New: '#34d399' };
  new Chart('segmentTrendChart', {
    type: 'line',
    data: {
      labels: D.monthly.map(m => m.month),
      datasets: D.segments.map(s => ({
        label: s.segment,
        data: D.monthly.map(m => Math.round(m.orders * (s.revenue / totalSeg))),
        borderColor: segColors[s.segment] || '#a855f7',
        backgroundColor: 'transparent',
        tension: .4,
        pointRadius: 3,
        borderWidth: 2
      }))
    },
    options: {
      responsive: true,
      plugins: { tooltip: tooltip() },
      scales: {
        x: { grid: { display: false }, ticks: tickOpts() },
        y: { grid: gridOpts(), ticks: tickOpts() }
      }
    }
  });

  const { kpis } = D;
  const custKpis = [
    { icon:'🏆', label:'Premium Customers', value: D.segments.find(s=>s.segment==='Premium')?.orders||'—', cls:'lavender' },
    { icon:'👣', label:'Regular Customers',  value: D.segments.find(s=>s.segment==='Regular')?.orders||'—', cls:'rose' },
    { icon:'🆕', label:'New Customers',      value: D.segments.find(s=>s.segment==='New')?.orders||'—', cls:'mint' },
    { icon:'💎', label:'Revenue / Customer', value: fmtCur(kpis.total_revenue / kpis.unique_customers), cls:'peach' },
  ];
  document.getElementById('custKpis').innerHTML = custKpis.map(k => `
    <div class="kpi-card ${k.cls}">
      <div class="kpi-icon">${k.icon}</div>
      <div class="kpi-label">${k.label}</div>
      <div class="kpi-value">${typeof k.value === 'number' ? fmtNum(k.value) : k.value}</div>
    </div>`).join('');
}

// ── SENSORS ───────────────────────────────────────────────────────
function buildSensorSection(D) {
  const sGrid = document.getElementById('sensorKpis');
  const totalSensorEvts = D.sensor_summary.reduce((a, s) => a + s.total, 0);
  const totalAlerts     = D.sensor_summary.reduce((a, s) => a + s.alerts, 0);
  const typesMost       = [...D.sensor_summary].sort((a,b) => b.alerts - a.alerts)[0];
  const alertRate       = ((totalAlerts / totalSensorEvts) * 100).toFixed(1);

  sGrid.innerHTML = [
    { icon:'📡', label:'Total Sensor Events', value: fmtNum(totalSensorEvts), cls:'sky' },
    { icon:'🚨', label:'Total Alerts',         value: fmtNum(totalAlerts),    cls:'coral' },
    { icon:'📊', label:'Alert Rate',           value: alertRate + '%',         cls:'lavender' },
    { icon:'🔥', label:'Most Alerts → Type',   value: typesMost.type,          cls:'rose' },
  ].map(k => `
    <div class="kpi-card ${k.cls}">
      <div class="kpi-icon">${k.icon}</div>
      <div class="kpi-label">${k.label}</div>
      <div class="kpi-value">${k.value}</div>
    </div>`).join('');

  // Alerts by sensor type (bar)
  new Chart('sensorAlertChart', {
    type: 'bar',
    data: {
      labels: D.sensor_summary.map(s => s.type),
      datasets: [
        { label: 'Total Events', data: D.sensor_summary.map(s => s.total),  backgroundColor: 'rgba(155,135,245,.3)', borderRadius: 8, borderSkipped: false },
        { label: 'Alerts',       data: D.sensor_summary.map(s => s.alerts), backgroundColor: '#f472b6',              borderRadius: 8, borderSkipped: false }
      ]
    },
    options: {
      responsive: true,
      plugins: { tooltip: tooltip() },
      scales: {
        x: { grid: { display: false }, ticks: tickOpts() },
        y: { grid: gridOpts(), ticks: tickOpts() }
      }
    }
  });

  // Alert rate % (radar)
  new Chart('alertRateChart', {
    type: 'radar',
    data: {
      labels: D.sensor_summary.map(s => s.type),
      datasets: [{
        label: 'Alert Rate %',
        data: D.sensor_summary.map(s => parseFloat(((s.alerts / s.total) * 100).toFixed(1))),
        backgroundColor: 'rgba(155,135,245,.15)',
        borderColor: '#9b87f5',
        pointBackgroundColor: '#9b87f5',
        pointBorderColor: '#ffffff',
        pointBorderWidth: 2,
        borderWidth: 2
      }]
    },
    options: {
      responsive: true,
      plugins: { legend: { display: false }, tooltip: tooltip() },
      scales: {
        r: {
          grid: { color: 'rgba(196,181,253,.3)' },
          pointLabels: { color: '#7c6fa0', font: { size: 11 } },
          ticks: { display: false, backdropColor: 'transparent' }
        }
      }
    }
  });

  // Warehouse × sensor type grouped bar
  const whs  = [...new Set(D.warehouse_alerts.map(w => w.warehouse))].sort();
  const stps = [...new Set(D.warehouse_alerts.map(w => w.sensor_type))].sort();
  const sColors = { CO2:'#f87171', Humidity:'#38bdf8', Light:'#fcd34d', Pressure:'#9b87f5', Temperature:'#fb923c', Vibration:'#34d399' };

  new Chart('warehouseAlertChart', {
    type: 'bar',
    data: {
      labels: whs,
      datasets: stps.map(st => ({
        label: st,
        data: whs.map(wh => {
          const row = D.warehouse_alerts.find(r => r.warehouse === wh && r.sensor_type === st);
          return row ? row.alerts : 0;
        }),
        backgroundColor: sColors[st] || '#94a3b8',
        borderRadius: 5
      }))
    },
    options: {
      responsive: true,
      plugins: { tooltip: tooltip() },
      scales: {
        x: { stacked: false, grid: { display: false }, ticks: tickOpts() },
        y: { stacked: false, grid: gridOpts(), ticks: tickOpts() }
      }
    }
  });
}

// ── QUERY SECTION ─────────────────────────────────────────────────
function buildQuerySection() {
  const queries = [
    {
      title: 'Q1 — Revenue KPIs (Total Metrics)',
      snippet: `SELECT
  COUNT(DISTINCT transaction_id)  AS total_orders,
  COUNT(DISTINCT customer_id)     AS unique_customers,
  ROUND(SUM(total_amount), 2)     AS total_revenue,
  ROUND(AVG(total_amount), 2)     AS avg_order_value,
  SUM(quantity)                   AS units_sold
FROM fact_transactions
WHERE status = 'Completed';`
    },
    {
      title: 'Q2 — Monthly Revenue Trend',
      snippet: `SELECT yr, mn,
  ROUND(SUM(total_amount), 2)  AS monthly_revenue,
  COUNT(transaction_id)         AS orders
FROM fact_transactions
WHERE status = 'Completed' AND yr = 2024
GROUP BY yr, mn
ORDER BY yr, mn;`
    },
    {
      title: 'Q3 — Revenue by Category',
      snippet: `SELECT category,
  COUNT(transaction_id)          AS total_orders,
  SUM(quantity)                  AS units_sold,
  ROUND(SUM(total_amount), 2)    AS revenue,
  ROUND(AVG(discount)*100, 2)   AS avg_discount_pct
FROM fact_transactions
WHERE status = 'Completed'
GROUP BY category
ORDER BY revenue DESC;`
    },
    {
      title: 'Q4 — Cumulative Revenue (Window Function)',
      snippet: `SELECT yr, mn, monthly_revenue,
  ROUND(SUM(monthly_revenue) OVER (
    ORDER BY yr, mn
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ), 2) AS cumulative_revenue
FROM (
  SELECT yr, mn, ROUND(SUM(total_amount),2) AS monthly_revenue
  FROM fact_transactions WHERE status='Completed'
  GROUP BY yr, mn
) t ORDER BY yr, mn;`
    },
    {
      title: 'Q5 — Customer Lifetime Value (CLV)',
      snippet: `SELECT c.customer_id, c.name, c.segment,
  COUNT(t.transaction_id)       AS total_orders,
  ROUND(SUM(t.total_amount),2)  AS lifetime_value,
  ROUND(AVG(t.total_amount),2)  AS avg_order
FROM fact_transactions t
JOIN dim_customers c ON t.customer_id = c.customer_id
WHERE t.status = 'Completed'
GROUP BY c.customer_id, c.name, c.segment
ORDER BY lifetime_value DESC
LIMIT 15;`
    },
    {
      title: 'Q6 — Sensor Alerts by Warehouse & Type',
      snippet: `SELECT warehouse_id, sensor_type,
  COUNT(event_id)                                          AS total_events,
  SUM(CAST(is_alert AS INT))                               AS alert_count,
  ROUND(SUM(CAST(is_alert AS INT))*100.0/COUNT(*), 2)     AS alert_rate_pct,
  ROUND(AVG(value), 2)                                     AS avg_value
FROM fact_sensor_events
GROUP BY warehouse_id, sensor_type
ORDER BY alert_count DESC;`
    },
    {
      title: 'Q7 — Real-time Micro-Batch (5-min windows)',
      snippet: `SELECT
  FROM_UNIXTIME(
    UNIX_TIMESTAMP(ts) - MOD(UNIX_TIMESTAMP(ts),300),
    'yyyy-MM-dd HH:mm'
  )                         AS window_5min,
  COUNT(transaction_id)     AS orders,
  ROUND(SUM(total_amount),2) AS revenue
FROM fact_transactions
WHERE ts >= DATE_SUB(CURRENT_TIMESTAMP, 1)
  AND status = 'Completed'
GROUP BY FROM_UNIXTIME(
  UNIX_TIMESTAMP(ts)-MOD(UNIX_TIMESTAMP(ts),300),'yyyy-MM-dd HH:mm')
ORDER BY window_5min;`
    },
    {
      title: 'Q8 — Quarter-over-Quarter Growth',
      snippet: `SELECT yr, CEIL(mn/3.0) AS quarter,
  ROUND(SUM(total_amount),2) AS revenue,
  ROUND(
    (SUM(total_amount) - LAG(SUM(total_amount)) OVER
      (ORDER BY yr, CEIL(mn/3.0))) /
    NULLIF(LAG(SUM(total_amount)) OVER
      (ORDER BY yr, CEIL(mn/3.0)), 0) * 100, 2
  ) AS qoq_growth_pct
FROM fact_transactions WHERE status='Completed'
GROUP BY yr, CEIL(mn/3.0)
ORDER BY yr, quarter;`
    }
  ];

  const list = document.getElementById('queryList');
  list.innerHTML = queries.map((q, i) => `
    <div class="query-item" id="qi${i}">
      <div class="query-title" onclick="toggleQuery(${i})">
        <div>${q.title}</div>
        <div style="display:flex;align-items:center;gap:10px">
          <span>HiveQL</span>
          <span class="query-chevron">▼</span>
        </div>
      </div>
      <div class="query-body">
        <pre>${sqlHighlight(q.snippet)}</pre>
      </div>
    </div>`).join('');
}

function toggleQuery(i) {
  const el = document.getElementById('qi' + i);
  el.classList.toggle('open');
}

function sqlHighlight(sql) {
  const keywords = /\b(SELECT|FROM|WHERE|GROUP BY|ORDER BY|JOIN|ON|AS|LIMIT|HAVING|LEFT|INNER|OUTER|BY|WITH|UNION|ALL|OVER|PARTITION|ROWS|BETWEEN|AND|OR|NOT|IN|IS|NULL|DISTINCT|ROUND|COUNT|SUM|AVG|MAX|MIN|CAST|NULLIF|LAG|SUM|CEIL|MOD|DATE_SUB|CURRENT_TIMESTAMP|CURRENT_DATE|INSERT|INTO|OVERWRITE|TABLE|CREATE|EXTERNAL|DROP|IF|EXISTS|USE|DATABASE|STORED|LOCATION)\b/g;
  return sql
    .replace(/--[^\n]*/g, m => `<span class="sql-comment">${m}</span>`)
    .replace(/'[^']*'/g, m => `<span class="sql-string">${m}</span>`)
    .replace(/\b\d+(\.\d+)?\b/g, m => `<span class="sql-number">${m}</span>`)
    .replace(keywords, m => `<span class="sql-keyword">${m}</span>`);
}

// ── NAV ───────────────────────────────────────────────────────────
function setupNav() {
  const links  = document.querySelectorAll('.nav-item');
  const crumb  = document.getElementById('breadcrumb');
  const labels = { overview:'Overview', revenue:'Revenue', categories:'Categories', geography:'Geography', customers:'Customers', sensors:'IoT Sensors', queries:'HiveQL Queries' };

  links.forEach(link => {
    link.addEventListener('click', e => {
      e.preventDefault();
      const sec = link.dataset.section;
      links.forEach(l => l.classList.remove('active'));
      link.classList.add('active');
      document.querySelectorAll('.section').forEach(s => s.classList.remove('active'));
      document.getElementById('section-' + sec).classList.add('active');
      crumb.textContent = labels[sec] || sec;
      // close sidebar on mobile
      if (window.innerWidth < 900) document.getElementById('sidebar').classList.remove('open');
    });
  });
}

function setupMenu() {
  document.getElementById('menuBtn').addEventListener('click', () => {
    document.getElementById('sidebar').classList.toggle('open');
  });
}
